# Get the latest python image
FROM python:latest

# Set the containers working directory
WORKDIR /app

# Copy hello.py into the working directory
COPY hello.py .

# Run the script
CMD ["python", "hello.py"]
